name: installer test
on: [push, pull_request]
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: run bash installer
        run: ./bashInstaller.sh --verbose --headless --no_update

  #I have no idea why this doesnt work but it doesnt so yeah
  #macOS:
  #  runs-on: macos-latest
  #  steps:
  #    - name: checkout repository
  #      uses: actions/checkout@v2
  #    - name: run bash installer
  #      run: ./bashInstaller.sh --verbose --headless --no_update

  Windows:
    runs-on: windows-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: run powershell installer
        shell: pwsh
        run: ./powershellInstaller.ps1 --verbose --headless --no_update
