name: installer test
on: [push, pull_request]
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: run bash installer
        run: ./bashInstaller.sh --verbose --headless --no_update

  macOS:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: run bash installer
        run: ./bashInstaller.sh --verbose --headless --no_update
